// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetClusters():Promise<Array<model.ClusterInfo>>;

export function GetCurrentEnvironment(arg1:string,arg2:string):Promise<model.EnvironmentDto>;

export function GetObjectsView():Promise<model.ObjectMapDto>;
