// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllEnvironment() {
  return window['go']['middleware']['EnvironmentMiddleware']['GetAllEnvironment']();
}

export function GetCurrentEnvironment(arg1, arg2) {
  return window['go']['middleware']['EnvironmentMiddleware']['GetCurrentEnvironment'](arg1, arg2);
}

export function GetObjectsView() {
  return window['go']['middleware']['EnvironmentMiddleware']['GetObjectsView']();
}
