// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteNamespace(arg1:string):Promise<void>;

export function ExportNamespaceObjects(arg1:string,arg2:string):Promise<void>;

export function GetNamespace(arg1:string):Promise<model.NamespaceDto>;

export function GetNamespaces():Promise<Array<model.NamespaceDto>>;

export function GetNode(arg1:string):Promise<model.NodeDtoV2>;

export function GetNodes():Promise<Array<model.NodeDtoV2>>;

export function UpdateNamespace(arg1:string,arg2:model.NamespaceDto):Promise<void>;
