// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNamespace(arg1, arg2) {
  return window['go']['middleware']['GeneralMiddleware']['DeleteNamespace'](arg1, arg2);
}

export function ExportNamespaceObjects(arg1, arg2, arg3) {
  return window['go']['middleware']['GeneralMiddleware']['ExportNamespaceObjects'](arg1, arg2, arg3);
}

export function GetNamespace(arg1, arg2) {
  return window['go']['middleware']['GeneralMiddleware']['GetNamespace'](arg1, arg2);
}

export function GetNamespaces(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['GetNamespaces'](arg1);
}

export function GetNode(arg1, arg2) {
  return window['go']['middleware']['GeneralMiddleware']['GetNode'](arg1, arg2);
}

export function GetNodes(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['GetNodes'](arg1);
}

export function UpdateNamespace(arg1, arg2, arg3) {
  return window['go']['middleware']['GeneralMiddleware']['UpdateNamespace'](arg1, arg2, arg3);
}
