// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNamespace(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['DeleteNamespace'](arg1);
}

export function ExportNamespaceObjects(arg1, arg2) {
  return window['go']['middleware']['GeneralMiddleware']['ExportNamespaceObjects'](arg1, arg2);
}

export function GetNamespace(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['GetNamespace'](arg1);
}

export function GetNamespaces() {
  return window['go']['middleware']['GeneralMiddleware']['GetNamespaces']();
}

export function GetNode(arg1) {
  return window['go']['middleware']['GeneralMiddleware']['GetNode'](arg1);
}

export function GetNodes() {
  return window['go']['middleware']['GeneralMiddleware']['GetNodes']();
}

export function UpdateNamespace(arg1, arg2) {
  return window['go']['middleware']['GeneralMiddleware']['UpdateNamespace'](arg1, arg2);
}
