// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteIngress(arg1, arg2) {
  return window['go']['middleware']['NetworkMiddleware']['DeleteIngress'](arg1, arg2);
}

export function DeleteService(arg1, arg2) {
  return window['go']['middleware']['NetworkMiddleware']['DeleteService'](arg1, arg2);
}

export function GetIngress(arg1, arg2) {
  return window['go']['middleware']['NetworkMiddleware']['GetIngress'](arg1, arg2);
}

export function GetIngresses(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['GetIngresses'](arg1);
}

export function GetService(arg1, arg2) {
  return window['go']['middleware']['NetworkMiddleware']['GetService'](arg1, arg2);
}

export function GetServices(arg1) {
  return window['go']['middleware']['NetworkMiddleware']['GetServices'](arg1);
}

export function UpdateIngress(arg1, arg2, arg3) {
  return window['go']['middleware']['NetworkMiddleware']['UpdateIngress'](arg1, arg2, arg3);
}

export function UpdateService(arg1, arg2, arg3) {
  return window['go']['middleware']['NetworkMiddleware']['UpdateService'](arg1, arg2, arg3);
}
