// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteIngress(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteService(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetIngress(arg1:string,arg2:string,arg3:string):Promise<model.IngressDto>;

export function GetIngresses(arg1:string):Promise<Array<model.IngressDto>>;

export function GetService(arg1:string,arg2:string,arg3:string):Promise<model.ServiceDto>;

export function GetServices(arg1:string):Promise<Array<model.ServiceDto>>;

export function UpdateIngress(arg1:string,arg2:string,arg3:model.IngressDto,arg4:string):Promise<void>;

export function UpdateService(arg1:string,arg2:string,arg3:model.ServiceUpdate,arg4:string):Promise<void>;
