// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePersistentVolume(arg1, arg2) {
  return window['go']['middleware']['StorageMiddleware']['DeletePersistentVolume'](arg1, arg2);
}

export function DeletePersistentVolumeClaim(arg1, arg2, arg3) {
  return window['go']['middleware']['StorageMiddleware']['DeletePersistentVolumeClaim'](arg1, arg2, arg3);
}

export function GetPersistentVolume(arg1, arg2) {
  return window['go']['middleware']['StorageMiddleware']['GetPersistentVolume'](arg1, arg2);
}

export function GetPersistentVolumeClaim(arg1, arg2, arg3) {
  return window['go']['middleware']['StorageMiddleware']['GetPersistentVolumeClaim'](arg1, arg2, arg3);
}

export function GetPersistentVolumes(arg1) {
  return window['go']['middleware']['StorageMiddleware']['GetPersistentVolumes'](arg1);
}

export function GetPersistentVolumesClaim(arg1) {
  return window['go']['middleware']['StorageMiddleware']['GetPersistentVolumesClaim'](arg1);
}

export function UpdatePersistentVolume(arg1, arg2, arg3) {
  return window['go']['middleware']['StorageMiddleware']['UpdatePersistentVolume'](arg1, arg2, arg3);
}

export function UpdatePersistentVolumeClaim(arg1, arg2, arg3, arg4) {
  return window['go']['middleware']['StorageMiddleware']['UpdatePersistentVolumeClaim'](arg1, arg2, arg3, arg4);
}
