// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AutoTroubleshoot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteDeployment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportManifest(arg1:string,arg2:string,arg3:string):Promise<Array<number>>;

export function GetDeployment(arg1:string,arg2:string,arg3:string):Promise<model.DeploymentDto>;

export function GetDeployments(arg1:string):Promise<Array<model.DeploymentDto>>;

export function GetPod(arg1:string,arg2:string,arg3:string):Promise<model.PodDto>;

export function GetPods(arg1:string):Promise<Array<model.PodDto>>;

export function ResourceTuning(arg1:string,arg2:string):Promise<void>;

export function RestartPod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateDeployment(arg1:string,arg2:string,arg3:model.DeploymentUpdate,arg4:string):Promise<void>;

export function UpdatePod(arg1:string,arg2:string,arg3:model.PodUpdate,arg4:string):Promise<void>;
