// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDeployment(arg1, arg2, arg3) {
  return window['go']['middleware']['WorkloadMiddleware']['DeleteDeployment'](arg1, arg2, arg3);
}

export function ExportManifest(arg1, arg2, arg3) {
  return window['go']['middleware']['WorkloadMiddleware']['ExportManifest'](arg1, arg2, arg3);
}

export function GetDeployment(arg1, arg2, arg3) {
  return window['go']['middleware']['WorkloadMiddleware']['GetDeployment'](arg1, arg2, arg3);
}

export function GetDeployments(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetDeployments'](arg1);
}

export function GetPod(arg1, arg2, arg3) {
  return window['go']['middleware']['WorkloadMiddleware']['GetPod'](arg1, arg2, arg3);
}

export function GetPods(arg1) {
  return window['go']['middleware']['WorkloadMiddleware']['GetPods'](arg1);
}

export function ResourceTuning(arg1, arg2) {
  return window['go']['middleware']['WorkloadMiddleware']['ResourceTuning'](arg1, arg2);
}

export function RestartPod(arg1, arg2, arg3) {
  return window['go']['middleware']['WorkloadMiddleware']['RestartPod'](arg1, arg2, arg3);
}

export function TroubleshootDeployment(arg1, arg2, arg3) {
  return window['go']['middleware']['WorkloadMiddleware']['TroubleshootDeployment'](arg1, arg2, arg3);
}

export function TroubleshootPod(arg1, arg2, arg3) {
  return window['go']['middleware']['WorkloadMiddleware']['TroubleshootPod'](arg1, arg2, arg3);
}

export function UpdateDeployment(arg1, arg2, arg3, arg4) {
  return window['go']['middleware']['WorkloadMiddleware']['UpdateDeployment'](arg1, arg2, arg3, arg4);
}

export function UpdatePod(arg1, arg2, arg3, arg4) {
  return window['go']['middleware']['WorkloadMiddleware']['UpdatePod'](arg1, arg2, arg3, arg4);
}
